### ISSUE TITLE
Push v0.7.2 to quay.io

### ISSUE THREAD

**Issue by sdlarsen** [kinvolk/flatcar-linux-update-operator#15]
It would be lovely to get easy access to every release, especially latest.

**Comment by invidian** [comment]
Hey @sdlarsen, we're aware, that the image is not published yet, I'm sorry about that. Unfortunately, during my testing, it turns out that there are more fixes required to get the operator working on Kubernetes 1.17 and we are now actively working on that.

Once that is fixed, I'll make another release and push the Docker images. You can track the progress of this work in the milestone I created: https://github.com/kinvolk/flatcar-linux-update-operator/milestone/1.

**Comment by invidian** [comment]
@sdlarsen [v0.7.3](https://github.com/kinvolk/flatcar-linux-update-operator/releases/tag/v0.7.3) is now released and available in quay.io, as 0.7.2 was faulty and we recommend all users to update to v0.7.3. Please let us know if it works for you now (if not, please create another issue).

As the latest image is available in quay.io, I'm going to close this issue now.

**Comment by sdlarsen** [comment]
Thanks!
